# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y1jRJvzhlUjdd66vnUOBj57YzwXHYc1s
"""

# app.py 
 (cd "$(git rev-parse --show-toplevel)" && git apply --3way <<'EOF' 
diff --git a/01app.py b/01app.py
index 8ee6364ec665bbee72381eabc70dc1ef3c7ca8c0..e295cc83492a0e5e54de4b7da2484f53428b6113 100644
--- a/01app.py
+++ b/01app.py
@@ -1,57 +1,59 @@
 # -*- coding: utf-8 -*-
 """app.ipynb
 
 Automatically generated by Colab.
 
 Original file is located at
     https://colab.research.google.com/drive/1Y1jRJvzhlUjdd66vnUOBj57YzwXHYc1s
 """
 
 # -*- coding: utf-8 -*-
 
 import streamlit as st
 import pandas as pd
 import numpy as np
 import yfinance as yf
 from datetime import datetime, timedelta
 from scipy.stats import spearmanr
 import plotly.graph_objects as go
 import altair as alt
 import requests
 import warnings
+import os
 warnings.filterwarnings('ignore')
 
 # ===============================
 # 基本設定
 # ===============================
 st.set_page_config(page_title="台灣 ETF 個人化推薦系統", layout="wide")
 st.title("📊 台灣 ETF 個人化推薦系統（修正版）")
 st.caption("⚠️ 本系統僅供學術研究參考，不構成投資建議。投資有風險，請審慎評估。")
 
 TRADING_DAYS = 252
 RISK_FREE_RATE = 0.015  # 修正：台灣 10 年期公債殖利率約 1.5%
+FINMIND_TOKEN = st.secrets.get("FINMIND_TOKEN", os.getenv("FINMIND_TOKEN", ""))
 
 # ===============================
 # ETF Universe & 市場基準
 # ===============================
 ETF_LIST = {
     "0050.TW": "股票型",
     "006208.TW": "股票型",
     "00692.TW": "股票型",
     "00757.TW": "股票型",
     "0056.TW": "高股息型",
     "00878.TW": "高股息型",
     "00919.TW": "高股息型",
 }
 MARKET_BENCHMARK = "0050.TW"
 
 # ===============================
 # 資料驗證機制（修正 #9）
 # ===============================
 def validate_metrics(ann_ret, ann_vol, sharpe, beta, etf_code):
     """
     驗證財務指標是否在合理範圍內
     """
     issues = []
     
     # 年化報酬率檢查
@@ -274,139 +276,128 @@ if st.sidebar.button("清除快取並更新報價"):
     st.sidebar.success("✅ 已清除快取")
 
 # ===============================
 # 資料來源說明
 # ===============================
 st.sidebar.markdown("---")
 st.sidebar.header("📡 資料來源")
 
 with st.sidebar.expander("查看資料來源說明"):
     st.caption(
         "**價格資料**：Yahoo Finance\n"
         "- 注意：可能延遲 15 分鐘\n"
         "- 建議用途：學術研究、回測分析\n\n"
         "**配息資料**：\n"
         "1. FinMind API（優先）\n"
         "2. 靜態資料（備用，每季更新）\n\n"
         "**資料品質聲明**：\n"
         "免費資料源可能存在延遲或誤差。\n"
         "如需即時且精準的資料，建議使用 TEJ 或券商 API。"
     )
 
 # ===============================
 # 抓取價格資料（改良快取策略）
 # ===============================
 
+@st.cache_data(ttl=1800)
+def fetch_price_history(code, period="1y"):
+    """單一標的歷史資料抓取（純資料快取，不含 UI 操作）"""
+    periods = [period, "6mo", "3mo"]
+    for attempt in periods:
+        try:
+            ticker = yf.Ticker(code)
+            df = ticker.history(period=attempt)
+            if not df.empty and len(df) >= 50 and 'Close' in df.columns:
+                return df
+        except Exception:
+            continue
+    return None
+
+
 @st.cache_data(ttl=1800)  # 修正：30 分鐘（歷史資料不需頻繁更新）
 def fetch_all_price_data(etf_list, benchmark, period="1y"):
-    """改良版資料抓取，加入錯誤處理"""
+    """改良版資料抓取，加入錯誤處理（純資料快取，不含 UI 操作）"""
     data = {}
     tickers = list(etf_list.keys()) + [benchmark]
-    
-    progress_bar = st.progress(0)
-    status_text = st.empty()
-    
-    for i, code in enumerate(set(tickers)):
-        try:
-            status_text.text(f"正在抓取 {code} 的歷史資料...")
-            ticker = yf.Ticker(code)
-            df = ticker.history(period=period)
-            
-            if not df.empty and len(df) >= 50:
-                # 使用調整後收盤價（Adjusted Close）
-                if 'Close' in df.columns:
-                    data[code] = df
-                else:
-                    st.warning(f"⚠️ {code} 缺少收盤價欄位")
-                    data[code] = None
-            else:
-                st.warning(f"⚠️ {code} 資料不足（< 50 筆）")
-                data[code] = None
-                
-        except Exception as e:
-            st.error(f"❌ {code} 資料抓取失敗: {str(e)}")
-            data[code] = None
-        
-        progress_bar.progress((i + 1) / len(set(tickers)))
-    
-    progress_bar.empty()
-    status_text.empty()
-    
+
+    for code in set(tickers):
+        data[code] = fetch_price_history(code, period=period)
+
     return data
 
 
 @st.cache_data(ttl=300)  # 修正：5 分鐘（Yahoo 本來就延遲）
 def fetch_latest_price(code):
     """抓取最新價格"""
     try:
         ticker = yf.Ticker(code)
-        
+
         # 方法 1: fast_info
         fast_info = getattr(ticker, "fast_info", None)
         if fast_info:
             for key in ("last_price", "lastPrice", "regularMarketPrice"):
                 price = fast_info.get(key)
                 if price and price > 0:
                     return float(price)
-        
+
         # 方法 2: 最近 5 天的收盤價
         hist = ticker.history(period="5d")
         if not hist.empty and 'Close' in hist.columns:
             return float(hist['Close'].iloc[-1])
-        
+
         return None
-        
-    except Exception as e:
+
+    except Exception:
         return None
 
 
 # ===============================
 # 配息資料抓取（改良版）
 # ===============================
 
-def get_price_from_finmind(stock_code):
+def get_price_from_finmind(stock_code, token=""):
     """從 FinMind 取得最新股價"""
     try:
         url = "https://api.finmindtrade.com/api/v4/data"
         params = {
             "dataset": "TaiwanStockPrice",
             "data_id": stock_code,
             "start_date": (datetime.now() - timedelta(days=7)).strftime('%Y-%m-%d'),
-            "token": ""
+            "token": token
         }
         
         response = requests.get(url, params=params, timeout=10)
         
         if response.status_code == 200:
             data = response.json()
             if data.get('status') == 200 and data.get('data'):
                 df_price = pd.DataFrame(data['data'])
                 if not df_price.empty and 'close' in df_price.columns:
                     return float(df_price.iloc[-1]['close'])
         
         return None
-    except:
+    except Exception:
         return None
 
 
 def get_static_dividend_data(stock_code):
     """
     手動維護的靜態配息資料
     更新日期：2025/02/10
     """
     static_data = {
         "0050": {
             "最新配息日": datetime(2024, 7, 22).date(),
             "最近一次配息": 3.00,
             "TTM配息": 5.50,
             "TTM殖利率%": 3.2,
             "資料日期": "2024-Q3"
         },
         "0056": {
             "最新配息日": datetime(2025, 1, 22).date(),  # 修正：更新為最新
             "最近一次配息": 2.00,  # 修正：2025/01 實際配息
             "TTM配息": 4.20,  # 修正：重新計算
             "TTM殖利率%": 6.5,  # 修正：基於最新價格
             "資料日期": "2025-Q1"
         },
         "006208": {
             "最新配息日": datetime(2024, 7, 22).date(),
@@ -433,125 +424,125 @@ def get_static_dividend_data(stock_code):
             "最新配息日": datetime(2024, 7, 22).date(),
             "最近一次配息": 0.48,
             "TTM配息": 0.96,
             "TTM殖利率%": 3.1,
             "資料日期": "2024-Q3"
         },
         "00757": {
             "最新配息日": datetime(2024, 8, 22).date(),
             "最近一次配息": 0.28,
             "TTM配息": 0.56,
             "TTM殖利率%": 2.5,
             "資料日期": "2024-Q3"
         }
     }
     
     return static_data.get(stock_code, {
         "最新配息日": None,
         "最近一次配息": 0.0,
         "TTM配息": 0.0,
         "TTM殖利率%": 0.0,
         "資料日期": "無資料"
     })
 
 
 @st.cache_data(ttl=7200)  # 修正：2 小時（配息資料不常變動）
-def fetch_dividend_info(etf_code):
+def fetch_dividend_info(etf_code, token=""):
     """
     多層次資料來源策略抓取 ETF 配息資料
     """
     stock_code = etf_code.replace('.TW', '')
     
     # 方法 1: FinMind API
     try:
         url = "https://api.finmindtrade.com/api/v4/data"
         params = {
             "dataset": "TaiwanStockDividend",
             "data_id": stock_code,
             "start_date": (datetime.now() - timedelta(days=400)).strftime('%Y-%m-%d'),
-            "token": ""
+            "token": token
         }
         
         response = requests.get(url, params=params, timeout=10)
         
         if response.status_code == 200:
             data = response.json()
             
             if data.get('status') == 200 and data.get('data') and len(data['data']) > 0:
                 df = pd.DataFrame(data['data'])
                 
                 if not df.empty:
                     # 處理日期欄位
                     if 'date' in df.columns:
                         df['date'] = pd.to_datetime(df['date'])
                     elif 'ex_dividend_date' in df.columns:
                         df['date'] = pd.to_datetime(df['ex_dividend_date'])
                     else:
                         raise ValueError("找不到日期欄位")
                     
                     df = df.sort_values('date', ascending=False)
                     
                     # 處理配息金額欄位
                     dividend_col = None
                     for col_name in ['cash_dividend', 'CashDividend', 'cash_dividend_amount']:
                         if col_name in df.columns:
                             dividend_col = col_name
                             break
                     
                     if dividend_col is None:
                         raise ValueError("找不到配息欄位")
                     
                     # 過濾有效配息記錄
                     df[dividend_col] = pd.to_numeric(df[dividend_col], errors='coerce')
                     df = df[df[dividend_col] > 0].dropna(subset=[dividend_col])
                     
                     if df.empty:
                         raise ValueError("沒有有效的配息記錄")
                     
                     # 計算 TTM
                     one_year_ago = datetime.now() - timedelta(days=365)
                     ttm_df = df[df['date'] >= one_year_ago]
                     ttm_sum = ttm_df[dividend_col].sum()
                     
                     # 取得最新價格
                     latest_price = fetch_latest_price(etf_code)
                     if latest_price is None or latest_price <= 0:
-                        latest_price = get_price_from_finmind(stock_code)
+                        latest_price = get_price_from_finmind(stock_code, token=token)
                         if latest_price is None or latest_price <= 0:
                             latest_price = 100
                     
                     ttm_yield = (ttm_sum / latest_price * 100) if latest_price > 0 else 0
                     
                     return {
                         "最新配息日": df.iloc[0]['date'].date(),
                         "最近一次配息": round(float(df.iloc[0][dividend_col]), 3),
                         "TTM配息": round(float(ttm_sum), 3),
                         "TTM殖利率%": round(ttm_yield, 2),
                         "資料來源": "FinMind"
                     }
     
-    except Exception as e:
+    except Exception:
         pass
     
     # 方法 2: 靜態資料
     result = get_static_dividend_data(stock_code)
     result["資料來源"] = "靜態資料"
     return result
 
 
 # ===============================
 # 指標計算（修正 Beta 計算）
 # ===============================
 def calc_metrics(df, market_df):
     """計算財務指標"""
     r = df["Close"].pct_change().dropna()
     mr = market_df["Close"].pct_change().dropna()
     idx = r.index.intersection(mr.index)
     r, mr = r.loc[idx], mr.loc[idx]
     
     ann_ret = r.mean() * TRADING_DAYS
     ann_vol = r.std() * np.sqrt(TRADING_DAYS)
     sharpe = (ann_ret - RISK_FREE_RATE) / ann_vol if ann_vol > 0 else 0
     
     # 修正：使用正確的 Beta 計算（ddof=1）
     beta = np.cov(r, mr)[0, 1] / np.var(mr, ddof=1)
     
@@ -647,89 +638,98 @@ def compute_personalized_score(ann_ret, ann_vol, sharpe, beta, theta):
         0.4 * sharpe_fit +
         0.3 * return_fit +
         0.2 * vol_fit +
         0.1 * beta_fit
     )
     
     return {
         "personal_score": personal_score,
         "sharpe_fit": sharpe_fit,
         "return_fit": return_fit,
         "vol_fit": vol_fit,
         "beta_fit": beta_fit
     }
 
 
 def compute_final_score(hot_index_norm, personal_score, alpha):
     """計算最終分數"""
     return alpha * hot_index_norm + (1 - alpha) * personal_score
 
 
 # ===============================
 # 主流程
 # ===============================
 with st.spinner("正在載入資料..."):
     price_data = fetch_all_price_data(ETF_LIST, MARKET_BENCHMARK)
-    market_df = price_data.get(MARKET_BENCHMARK)
 
+missing_codes = [code for code, df in price_data.items() if df is None]
+if missing_codes:
+    st.warning(f"⚠️ 以下標的歷史資料不足或抓取失敗：{', '.join(sorted(missing_codes))}")
+
+market_df = price_data.get(MARKET_BENCHMARK)
 if market_df is None:
-    st.error("❌ 無法取得市場基準（0050）資料，請檢查網路連線或稍後重試")
-    st.stop()
+    fallback_market_df = next((df for df in price_data.values() if df is not None), None)
+    if fallback_market_df is not None:
+        st.warning("⚠️ 無法取得市場基準（0050）資料，改用其他可用 ETF 作為替代基準。")
+        market_df = fallback_market_df
+    else:
+        st.error("❌ 無法取得任何 ETF 歷史資料，請檢查網路連線或稍後重試")
+        st.stop()
 
 rows = []
 for etf, etf_type in ETF_LIST.items():
     df = price_data.get(etf)
     if df is None or market_df is None:
         continue
     
     # 取得最新價格
     latest_price = fetch_latest_price(etf)
     if latest_price is None:
         latest_price = float(df["Close"].iloc[-1])
     
     # 計算指標
     ann_ret, ann_vol, sharpe, beta = calc_metrics(df, market_df)
     
     # 資料驗證（#9）
     is_valid = validate_metrics(ann_ret, ann_vol, sharpe, beta, etf)
     if not is_valid:
         # 如果資料異常，仍保留但標記
         pass
     
     # 計算個人化分數
     comp = compute_personalized_score(ann_ret, ann_vol, sharpe, beta, theta)
     
     # 計算風險適配分數
     risk_score = (
         comp["vol_fit"] * 0.4 +
         comp["beta_fit"] * 0.3 +
         comp["return_fit"] * 0.2 +
         comp["sharpe_fit"] * 0.1
     )
     
     # 取得配息資訊
-    div_info = fetch_dividend_info(etf)
+    div_info = fetch_dividend_info(etf, token=FINMIND_TOKEN)
     
    

    # 計算 HotIndex
    hot_metrics = compute_hot_index(df)
    
    row = {
        "ETF": etf,
        "類型": etf_type,
        "最新價": round(latest_price, 2),
        "最新配息日": div_info["最新配息日"],
        "最近一次配息": div_info["最近一次配息"],
        "TTM配息": div_info["TTM配息"],
        "TTM殖利率%": div_info["TTM殖利率%"],
        "配息資料來源": div_info.get("資料來源", "未知"),
        "資料日期": div_info.get("資料日期", ""),
        "Sharpe": round(sharpe, 2),
        "Beta": round(beta, 2),
        "年化報酬%": round(ann_ret, 2),
        "年化波動%": round(ann_vol, 2),
        "個人化分數": round(comp["personal_score"], 3),
        "風險適配分數": round(risk_score, 3),
        "hot_index_raw": hot_metrics["hot_index"],
        "Sharpe適配": round(comp["sharpe_fit"], 2),
        "報酬適配": round(comp["return_fit"], 2),
        "波動適配": round(comp["vol_fit"], 2),
        "Beta適配": round(comp["beta_fit"], 2),
        "資料有效": is_valid
    }
    rows.append(row)

df_all = pd.DataFrame(rows)

if df_all.empty:
    st.error("❌ 無法取得任何 ETF 資料")
    st.stop()

# 標準化 HotIndex
df_all["hot_index_norm"] = robust_zscore(df_all["hot_index_raw"]).fillna(0)

# ===============================
# 修正：排序邏輯（#16）
# ===============================
THETA_LIST = [0.0, 0.25, 0.5, 0.75, 1.0]
theta_rankings = {}

for t in THETA_LIST:
    rows_theta = []
    # 修正：每個 θ 值對應不同的 α
    alpha_t = alpha_from_theta(t)
    
    for etf, etf_type in ETF_LIST.items():
        df = price_data.get(etf)
        if df is None or market_df is None:
            continue
        
        ann_ret, ann_vol, sharpe, beta = calc_metrics(df, market_df)
        
        # 使用對應的 θ 計算個人化分數
        comp = compute_personalized_score(ann_ret, ann_vol, sharpe, beta, t)
        
        # 使用對應的 α 計算最終分數
        final_score = compute_final_score(
            df_all.loc[df_all["ETF"] == etf, "hot_index_norm"].values[0],
            comp["personal_score"],
            alpha_t  # 修正：使用對應的 α
        )
        
        base_row = df_all[df_all["ETF"] == etf].iloc[0]
        row = {
            "ETF": etf,
            "類型": etf_type,
            "θ": t,
            "α": alpha_t,  # 新增：顯示對應的 α
            "最新價": base_row["最新價"],
            "最新配息日": base_row["最新配息日"],
            "最近一次配息": base_row["最近一次配息"],
            "TTM配息": base_row["TTM配息"],
            "TTM殖利率%": base_row["TTM殖利率%"],
            "final_score": final_score,
            **comp,
            "hot_index": base_row["hot_index_raw"],
            "hot_index_norm": base_row["hot_index_norm"]
        }
        rows_theta.append(row)
    
    df_theta = pd.DataFrame(rows_theta).sort_values("final_score", ascending=False)
    theta_rankings[t] = df_theta

# 取得最接近用戶 θ 的排序結果
theta_display_closest = min(THETA_LIST, key=lambda x: abs(x - theta))
df_ui_base = theta_rankings[theta_display_closest]

# 修正：實作真正的排序選項（#15）
sort_mapping = {
    "綜合分數（HotIndex + 個人化）": ("final_score", False),
    "個人化分數": ("personal_score", False),
    "HotIndex 分數": ("hot_index_norm", False),
    "風險適配分數": ("風險適配分數", False),
    "Sharpe Ratio": ("Sharpe", False),
    "年化報酬率": ("年化報酬%", False),
    "TTM 殖利率": ("TTM殖利率%", False)
}

sort_col, sort_asc = sort_mapping[sort_option]

# 合併排序欄位（從 df_all）
df_ui_sorted = df_ui_base.copy()
if sort_col in df_all.columns:
    for idx, row in df_ui_sorted.iterrows():
        etf_code = row["ETF"]
        df_ui_sorted.loc[idx, sort_col] = df_all.loc[df_all["ETF"] == etf_code, sort_col].values[0]

df_ui = df_ui_sorted.sort_values(sort_col, ascending=sort_asc).head(TOP_N)

# ===============================
# 雷達圖資料
# ===============================
radar_metrics = ["sharpe_fit", "return_fit", "vol_fit", "beta_fit"]
df_radar = df_ui.copy()
for col in radar_metrics:
    min_v = df_radar[col].min()
    max_v = df_radar[col].max()
    if max_v > min_v:
        df_radar[col] = (df_radar[col] - min_v) / (max_v - min_v)
    else:
        df_radar[col] = 0.5

# ===============================
# Top-N 表格
# ===============================
st.subheader(f"🎯 Top {TOP_N} ETF 排序")
st.caption(
    f"**排序依據**：{sort_option} | "
    f"**風險類型**：{risk_profile} (θ={theta:.2f}) | "
    f"**α權重**：{ALPHA_MODEL:.2f}"
)

# 顯示表格
display_cols = [
    "ETF", "類型", "最新價", "最新配息日", "最近一次配息",
    "TTM配息", "TTM殖利率%", "final_score", "personal_score",
    "年化報酬%", "年化波動%", "Sharpe", "Beta"
]

# 合併必要欄位
for col in ["年化報酬%", "年化波動%", "Sharpe", "Beta"]:
    if col not in df_ui.columns:
        for idx, row in df_ui.iterrows():
            etf_code = row["ETF"]
            df_ui.loc[idx, col] = df_all.loc[df_all["ETF"] == etf_code, col].values[0]

st.dataframe(
    df_ui[display_cols].style.format({
        "最新價": "{:.2f}",
        "最近一次配息": "{:.3f}",
        "TTM配息": "{:.3f}",
        "TTM殖利率%": "{:.2f}%",
        "final_score": "{:.3f}",
        "personal_score": "{:.3f}",
        "年化報酬%": "{:.2f}%",
        "年化波動%": "{:.2f}%",
        "Sharpe": "{:.2f}",
        "Beta": "{:.2f}"
    }),
    use_container_width=True
)

# 配息資料來源統計
api_count = df_all[df_all["配息資料來源"] == "FinMind"].shape[0]
static_count = df_all[df_all["配息資料來源"] == "靜態資料"].shape[0]

col1, col2, col3 = st.columns(3)
with col1:
    st.metric("FinMind API 成功", api_count)
with col2:
    st.metric("靜態資料使用", static_count)
with col3:
    invalid_count = df_all[~df_all["資料有效"]].shape[0]
    st.metric("資料異常警告", invalid_count)

if static_count > 0:
    st.info(
        f"⚠️ 有 {static_count} 檔 ETF 使用靜態配息資料。"
        "建議查閱各 ETF 官網取得最新公告。"
    )

# ===============================
# 雷達圖
# ===============================
st.subheader(f"🕸️ Top {TOP_N} ETF 多指標雷達圖")
radar_labels = ["Sharpe", "Return", "Volatility", "Beta"]
fig = go.Figure()

for _, row in df_radar.iterrows():
    values = [row[m] for m in radar_metrics]
    values.append(values[0])
    fig.add_trace(go.Scatterpolar(
        r=values,
        theta=radar_labels + [radar_labels[0]],
        fill="toself",
        name=row["ETF"],
        opacity=0.6
    ))

fig.update_layout(
    polar=dict(radialaxis=dict(visible=True, range=[0, 1])),
    showlegend=True,
    margin=dict(l=40, r=40, t=40, b=60)
)
st.plotly_chart(fig, use_container_width=True)

# ===============================
# 氣泡圖
# ===============================
st.subheader(f"💭 Top {TOP_N} ETF 績效分析圖")

# 準備氣泡圖資料
bubble_data = df_ui.copy()
for col in ["年化報酬%", "年化波動%", "TTM殖利率%"]:
    if col not in bubble_data.columns:
        for idx, row in bubble_data.iterrows():
            etf_code = row["ETF"]
            bubble_data.loc[idx, col] = df_all.loc[df_all["ETF"] == etf_code, col].values[0]

bubble = alt.Chart(bubble_data).mark_circle(opacity=0.7, stroke="black", strokeWidth=1).encode(
    x=alt.X("年化報酬%:Q", title="年化報酬率 (%)", scale=alt.Scale(zero=False)),
    y=alt.Y("年化波動%:Q", title="年化波動率 (%)", scale=alt.Scale(zero=False)),
    size=alt.Size("TTM殖利率%:Q", title="TTM 殖利率 (%)", scale=alt.Scale(range=[100, 2000])),
    color=alt.Color("類型:N", title="ETF 類型"),
    tooltip=[
        "ETF", "類型", "年化報酬%", "年化波動%",
        "Sharpe", "TTM殖利率%", "personal_score", "final_score"
    ]
)

st.altair_chart(bubble, use_container_width=True)

# ===============================
# 全部 ETF 比較表
# ===============================
st.divider()
st.subheader("📊 完整 ETF 比較表")

comparison_cols = [
    "ETF", "類型", "最新價", "年化報酬%", "年化波動%",
    "Sharpe", "Beta", "TTM殖利率%", "個人化分數",
    "hot_index_norm", "資料有效", "配息資料來源"
]

st.dataframe(
    df_all[comparison_cols].sort_values("個人化分數", ascending=False).style.format({
        "最新價": "{:.2f}",
        "年化報酬%": "{:.2f}%",
        "年化波動%": "{:.2f}%",
        "Sharpe": "{:.2f}",
        "Beta": "{:.2f}",
        "TTM殖利率%": "{:.2f}%",
        "個人化分數": "{:.3f}",
        "hot_index_norm": "{:.3f}"
    }).applymap(
        lambda x: "background-color: #ffcccc" if x == False else "",
        subset=["資料有效"]
    ),
    use_container_width=True
)

# ===============================
# 系統說明
# ===============================
st.divider()
st.subheader("📖 系統說明")

with st.expander("🔧 修正內容總覽"):
    st.markdown("""
    **本版本主要修正：**
    
    1. ✅ **排序邏輯修正**：每個 θ 值現在對應不同的 α 權重
    2. ✅ **個人化分數修正**：不再懲罰超額報酬，基於台灣市場實際數據調整期望值
    3. ✅ **HotIndex 重新設計**：所有指標標準化後再加權，避免量綱問題
    4. ✅ **資料驗證機制**：檢查財務指標是否在合理範圍
    5. ✅ **真實排序選項**：所有排序選項均可正常運作
    6. ✅ **學術引用修正**：誠實說明問卷設計來源與調整
    7. ✅ **Beta 計算修正**：使用正確的樣本變異數（ddof=1）
    8. ✅ **配息資料更新**：更新至 2025/02/10
    9. ✅ **快取策略優化**：根據資料更新頻率調整 TTL
    """)

with st.expander("⚠️ 使用限制與免責聲明"):
    st.markdown("""
    **資料來源限制：**
    - Yahoo Finance 資料可能延遲或缺漏
    - FinMind 免費版更新較慢
    - 靜態配息資料需定期手動更新
    
    **方法論限制：**
    - 風險偏好問卷為簡化版，非完整心理測量量表
    - 理想值設定基於歷史數據，不保證未來適用
    - HotIndex 設計為研究用途，實際效果需回測驗證
    
    **免責聲明：**
    - 本系統僅供學術研究與教育用途
    - 不構成投資建議或推薦
    - 投資決策應基於您自身的研究與判斷
    - 投資有風險，請審慎評估
    """)

with st.expander("🚀 未來改進方向"):
    st.markdown("""
    **建議改進項目：**
    
    1. **資料品質提升**
       - 整合 TEJ 台灣經濟新報 API
       - 加入券商即時報價
       - 自動更新配息資料
    
    2. **功能擴充**
       - 歷史績效回測
       - 投資組合建議
       - 風險壓力測試
       - Excel 匯出功能
    
    3. **演算法改進**
       - 機器學習預測模型
       - 動態權重調整
       - 多因子模型整合
    
    4. **使用者體驗**
       - 儲存個人化設定
       - 比較不同情境
       - 客製化報表
    """)

# ===============================
# 頁尾
# ===============================
st.divider()
st.caption(
    "💡 **資料更新日期**：2025/02/10 | "
    "**系統版本**：v2.0 (修正版) | "
    "**開發者**：財金資工研究團隊"
)
